[package]
name = "rust-backend"
version = "0.1.0"
edition = "2021"
# respository = "https://github.com/Noban130/rust-backend"

[dependencies]
solana-client = "2.0"
solana-sdk = "1.14"
solana-program = "2"
borsh="1.5"
mpl-token-metadata = "4"